### PR TITLE
Removing kentik, replacing with ground_control_sp_location and Adding ds Support with sorted fields

### PR DESCRIPTION
**Pull request by stephen-pl**
Removing kentik, replacing with ground_control_sp_location and Adding ds Support with sorted fields

Rename kentik and replacing it with ground_control_sp_location. Kentik schema was deleted and replaced with ground_control_sp_location.

Updating gen Script To support DateStamp (ds)

Updating gen script to support a new field called ds which stands for datestamp. This field will be used to make it easier to query by dates in the YYYY-MM-DD time stamp. The params and fields are also sorted in this pr with the exception of id which is considered the id for the collection.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/data-preservation-programs/RepPoly/pull/5).
* __->__ #5
* #2

### CODE REVIEW

**Comment by stephen-pl** [comment]
This is a combination of the rename and the reordering we talked about on https://github.com/data-preservation-programs/RepPoly/pull/3

**Comment by stephen-pl** [comment]
Adding @xmcai2016 for viability. @xinaxu  for the bots I added a ds which is basically the copy of the data column since it was in the right format. Do we value consistency of naming across the collections or reduction of data stored and leave it up to the devs to know that some collections will use date and others will use ds.

**Comment by xinaxu** [comment]
Have you looked at the actual data to see if YYYY-MM-DD makes sense? I worry that the actual data may have time fields that are more granular than date. Also, whether we should use a string or number needs to be decided by how we expect people to consume it. Better confirm with @xmcai2016 . Or we can have both string and number field if that is unsure

**Comment by stephen-pl** [comment]
I have looked at the data. The original columns still exist so I am not worries about losing the information. We could do ISO UTC standards instead of truncating it down. The conversation I had with @xmcai2016 we discussed YYYY-MM-DD seemed to be what we want for the hackathon.

**Comment by xinaxu** [comment]
If you look at `lassie` collection latest entries, each entry is a lassie retrieval attempt. So there will be multiple entries for same SPs giving a start_time. How do you plan to handle that case?

**Comment by xinaxu** [comment]
Oh, also, they just added `sp_id` for lassie collection but the gen.ts is looking at the earliest entries that do not have `sp_id`. We may need to change the logic to get from last entry.

**Comment by stephen-pl** [comment]
> If you look at `lassie` collection latest entries, each entry is a lassie retrieval attempt. So there will be multiple entries for same SPs giving a start_time. How do you plan to handle that case?

Does that matter? The ds isnt a unique identifier. During the hackathon the hackathoner could still use start time if that precision is desired.

**Comment by stephen-pl** [comment]
> Oh, also, they just added `sp_id` for lassie collection but the gen.ts is looking at the earliest entries that do not have `sp_id`. We may need to change the logic to get from last entry. Or if you think it's time to drop schema automation and rely on human for those new changes, feel free to do that too

This is an issue with the filscan data as well. The schema changed and the _id. I talked with caro about filscan and she said dont bring over the old data. Polybase is fincky with the fields and values. I am fine with either but we should discuss how we want to handle backfilling data. Do we drop the collection and rebuild with proper defaults. Do we ignore data that doesnt adhere to schema or are we ok with what polybase does when you modify the schema (I think its just nulls)

**Comment by stephen-pl** [comment]
im going to move this to draft until we lock down on how to handle schema changes

**Pull request closed without merging**
